In [42]:
import numpy
import matplotlib.pyplot as plt
import gymnasium
from gymnasium.wrappers import RecordVideo
from gymnasium.utils.play import play

In [43]:
#  sets the precision to 3 decimal places.
numpy.set_printoptions(precision=3)

In [44]:
env = gymnasium.make("ALE/SpaceInvaders-v5", render_mode='rgb_array')

# SpaceInvaders has the action space Discrete(6)

| Value | Meaning    |
|-------|------------|
| 0     | NOOP       |
| 1     | FIRE       |
| 2     | RIGHT      |
| 3     | LEFT       |
| 4     | RIGHTFIRE  |
| 5     | LEFTFIRE   |


# ENV reset variables

In [45]:
obs, info = env.reset()

In [46]:
print(obs)

[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]]


In [47]:
print(info)

{'lives': 3, 'episode_frame_number': 0, 'frame_number': 0}


# ENV step variables

In [48]:
action = env.action_space.sample() # Just a random agent
obs, reward, terminated, truncated, info = env.step(action)

In [49]:
print(obs)

[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]]


In [50]:
print(reward)

0.0


In [51]:
print(terminated)

False


In [52]:
print(truncated)

False


In [53]:
print(info)

{'lives': 3, 'episode_frame_number': 4, 'frame_number': 4}


# Difficulty

In [54]:

# To add diffculty to the game we must declar it, 0 is default difculty or 1 is
difficulty=1

env = gymnasium.make("ALE/SpaceInvaders-v5", render_mode='rgb_array', difficulty = difficulty)

# High Score

In [56]:
# To get access to env settings we use spec

print(env.spec)

# Gaining Access to diffuclty

read_difficulty = env.unwrapped.spec.kwargs['difficulty']

# Getting into into the data

print(type(read_difficulty))
print(read_difficulty)


EnvSpec(id='ALE/SpaceInvaders-v5', entry_point='shimmy.atari_env:AtariEnv', reward_threshold=None, nondeterministic=False, max_episode_steps=None, order_enforce=True, autoreset=False, disable_env_checker=False, apply_api_compatibility=False, kwargs={'game': 'space_invaders', 'obs_type': 'rgb', 'repeat_action_probability': 0.25, 'full_action_space': False, 'frameskip': 4, 'max_num_frames_per_episode': 108000, 'render_mode': 'rgb_array', 'difficulty': 1}, namespace='ALE', name='SpaceInvaders', version=5, additional_wrappers=(), vector_entry_point=None)
<class 'int'>
1
