In [27]:
import numpy
import matplotlib.pyplot as plt
import gymnasium
from gymnasium.wrappers import RecordVideo
from gymnasium.utils.play import play

In [28]:
#  sets the precision to 3 decimal places.
numpy.set_printoptions(precision=3)

In [29]:
env = gymnasium.make("ALE/SpaceInvaders-v5", render_mode='rgb_array')

# SpaceInvaders has the action space Discrete(6)

| Value | Meaning    |
|-------|------------|
| 0     | NOOP       |
| 1     | FIRE       |
| 2     | RIGHT      |
| 3     | LEFT       |
| 4     | RIGHTFIRE  |
| 5     | LEFTFIRE   |


# ENV reset variables

In [30]:
obs, info = env.reset()

In [31]:
print(obs)

[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]]


In [32]:
print(info)

{'lives': 3, 'episode_frame_number': 0, 'frame_number': 0}


# ENV step variables

In [33]:
action = env.action_space.sample() # Just a random agent
obs, reward, terminated, truncated, info = env.step(action)

In [34]:
print(obs)

[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]]


In [35]:
print(reward)

0.0


In [36]:
print(terminated)

False


In [37]:
print(truncated)

False


In [38]:
print(info)

{'lives': 3, 'episode_frame_number': 4, 'frame_number': 4}


# Difficulty

In [40]:

# To add diffculty to the game we must declar it, 0 is default difculty or 1 is the optional
difficulty=1

env = gymnasium.make("ALE/SpaceInvaders-v5", render_mode='rgb_array', difficulty = difficulty)